### PR TITLE
Introduce COMMAND_DELAY

### PR DESCRIPTION
**Pull request by joncave**
Add a new command packet to allow for modification of the client's session delay on-the-fly.

This allows the operator to send the client to 'sleep' while its not in use, thus reducing the amount of DNS communication. They can then bring it 'back to life' if it's required again. This is done by simply specifying a check-in time in seconds to the delay command on the server.

Currently it only accepts one second or greater delay, but this could be updated to support 'zero' delay (which would probably be 500ms in the background) for even more interactive sessions.

### CODE REVIEW

**Comment by iagox86** [comment]
Very cool! I'll need a bit more time to look at this before I merge it. :)

**Comment by joncave** [comment]
No worries. I expect that it could be improved by actually sleeping somewhere (to reduce unnecessary CPU use), but simply increasing the session delay worked to drop DNS request frequency.

**Comment by iagox86** [comment]
Hey, everything looks good!

Just a quick/simple request: Can you update doc/changelog.md and contributors.md to give yourself credit?

**Comment by joncave** [comment]
Great. Made those changes for you too.

**Comment by iagox86** [comment]
Great, thanks a lot! Sorry it took a couple weeks. :)

**Pull request merged**
